# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/leicht/Documents/Stephane/prog/fox/df1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/leicht/Documents/Stephane/prog/fox/df1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leicht/Documents/Stephane/prog/fox/df1/CMakeFiles /home/leicht/Documents/Stephane/prog/fox/df1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leicht/Documents/Stephane/prog/fox/df1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named df1

# Build rule for target.
df1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 df1
.PHONY : df1

# fast build rule for target.
df1/fast:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/build
.PHONY : df1/fast

src/calc_address.o: src/calc_address.c.o
.PHONY : src/calc_address.o

# target to build an object file
src/calc_address.c.o:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/calc_address.c.o
.PHONY : src/calc_address.c.o

src/calc_address.i: src/calc_address.c.i
.PHONY : src/calc_address.i

# target to preprocess a source file
src/calc_address.c.i:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/calc_address.c.i
.PHONY : src/calc_address.c.i

src/calc_address.s: src/calc_address.c.s
.PHONY : src/calc_address.s

# target to generate assembly for a file
src/calc_address.c.s:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/calc_address.c.s
.PHONY : src/calc_address.c.s

src/common.o: src/common.c.o
.PHONY : src/common.o

# target to build an object file
src/common.c.o:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/common.c.o
.PHONY : src/common.c.o

src/common.i: src/common.c.i
.PHONY : src/common.i

# target to preprocess a source file
src/common.c.i:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/common.c.i
.PHONY : src/common.c.i

src/common.s: src/common.c.s
.PHONY : src/common.s

# target to generate assembly for a file
src/common.c.s:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/common.c.s
.PHONY : src/common.c.s

src/df1.o: src/df1.c.o
.PHONY : src/df1.o

# target to build an object file
src/df1.c.o:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/df1.c.o
.PHONY : src/df1.c.o

src/df1.i: src/df1.c.i
.PHONY : src/df1.i

# target to preprocess a source file
src/df1.c.i:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/df1.c.i
.PHONY : src/df1.c.i

src/df1.s: src/df1.c.s
.PHONY : src/df1.s

# target to generate assembly for a file
src/df1.c.s:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/df1.c.s
.PHONY : src/df1.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/main.c.s
.PHONY : src/main.c.s

src/read_A2.o: src/read_A2.c.o
.PHONY : src/read_A2.o

# target to build an object file
src/read_A2.c.o:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/read_A2.c.o
.PHONY : src/read_A2.c.o

src/read_A2.i: src/read_A2.c.i
.PHONY : src/read_A2.i

# target to preprocess a source file
src/read_A2.c.i:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/read_A2.c.i
.PHONY : src/read_A2.c.i

src/read_A2.s: src/read_A2.c.s
.PHONY : src/read_A2.s

# target to generate assembly for a file
src/read_A2.c.s:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/read_A2.c.s
.PHONY : src/read_A2.c.s

src/read_boolean.o: src/read_boolean.c.o
.PHONY : src/read_boolean.o

# target to build an object file
src/read_boolean.c.o:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/read_boolean.c.o
.PHONY : src/read_boolean.c.o

src/read_boolean.i: src/read_boolean.c.i
.PHONY : src/read_boolean.i

# target to preprocess a source file
src/read_boolean.c.i:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/read_boolean.c.i
.PHONY : src/read_boolean.c.i

src/read_boolean.s: src/read_boolean.c.s
.PHONY : src/read_boolean.s

# target to generate assembly for a file
src/read_boolean.c.s:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/read_boolean.c.s
.PHONY : src/read_boolean.c.s

src/read_float.o: src/read_float.c.o
.PHONY : src/read_float.o

# target to build an object file
src/read_float.c.o:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/read_float.c.o
.PHONY : src/read_float.c.o

src/read_float.i: src/read_float.c.i
.PHONY : src/read_float.i

# target to preprocess a source file
src/read_float.c.i:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/read_float.c.i
.PHONY : src/read_float.c.i

src/read_float.s: src/read_float.c.s
.PHONY : src/read_float.s

# target to generate assembly for a file
src/read_float.c.s:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/read_float.c.s
.PHONY : src/read_float.c.s

src/read_integer.o: src/read_integer.c.o
.PHONY : src/read_integer.o

# target to build an object file
src/read_integer.c.o:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/read_integer.c.o
.PHONY : src/read_integer.c.o

src/read_integer.i: src/read_integer.c.i
.PHONY : src/read_integer.i

# target to preprocess a source file
src/read_integer.c.i:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/read_integer.c.i
.PHONY : src/read_integer.c.i

src/read_integer.s: src/read_integer.c.s
.PHONY : src/read_integer.s

# target to generate assembly for a file
src/read_integer.c.s:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/read_integer.c.s
.PHONY : src/read_integer.c.s

src/read_socket.o: src/read_socket.c.o
.PHONY : src/read_socket.o

# target to build an object file
src/read_socket.c.o:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/read_socket.c.o
.PHONY : src/read_socket.c.o

src/read_socket.i: src/read_socket.c.i
.PHONY : src/read_socket.i

# target to preprocess a source file
src/read_socket.c.i:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/read_socket.c.i
.PHONY : src/read_socket.c.i

src/read_socket.s: src/read_socket.c.s
.PHONY : src/read_socket.s

# target to generate assembly for a file
src/read_socket.c.s:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/read_socket.c.s
.PHONY : src/read_socket.c.s

src/select_fnct.o: src/select_fnct.c.o
.PHONY : src/select_fnct.o

# target to build an object file
src/select_fnct.c.o:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/select_fnct.c.o
.PHONY : src/select_fnct.c.o

src/select_fnct.i: src/select_fnct.c.i
.PHONY : src/select_fnct.i

# target to preprocess a source file
src/select_fnct.c.i:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/select_fnct.c.i
.PHONY : src/select_fnct.c.i

src/select_fnct.s: src/select_fnct.c.s
.PHONY : src/select_fnct.s

# target to generate assembly for a file
src/select_fnct.c.s:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/select_fnct.c.s
.PHONY : src/select_fnct.c.s

src/serial.o: src/serial.c.o
.PHONY : src/serial.o

# target to build an object file
src/serial.c.o:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/serial.c.o
.PHONY : src/serial.c.o

src/serial.i: src/serial.c.i
.PHONY : src/serial.i

# target to preprocess a source file
src/serial.c.i:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/serial.c.i
.PHONY : src/serial.c.i

src/serial.s: src/serial.c.s
.PHONY : src/serial.s

# target to generate assembly for a file
src/serial.c.s:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/serial.c.s
.PHONY : src/serial.c.s

src/server.o: src/server.c.o
.PHONY : src/server.o

# target to build an object file
src/server.c.o:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/server.c.o
.PHONY : src/server.c.o

src/server.i: src/server.c.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.c.i:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/server.c.i
.PHONY : src/server.c.i

src/server.s: src/server.c.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.c.s:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/server.c.s
.PHONY : src/server.c.s

src/write_AA.o: src/write_AA.c.o
.PHONY : src/write_AA.o

# target to build an object file
src/write_AA.c.o:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/write_AA.c.o
.PHONY : src/write_AA.c.o

src/write_AA.i: src/write_AA.c.i
.PHONY : src/write_AA.i

# target to preprocess a source file
src/write_AA.c.i:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/write_AA.c.i
.PHONY : src/write_AA.c.i

src/write_AA.s: src/write_AA.c.s
.PHONY : src/write_AA.s

# target to generate assembly for a file
src/write_AA.c.s:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/write_AA.c.s
.PHONY : src/write_AA.c.s

src/write_AB.o: src/write_AB.c.o
.PHONY : src/write_AB.o

# target to build an object file
src/write_AB.c.o:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/write_AB.c.o
.PHONY : src/write_AB.c.o

src/write_AB.i: src/write_AB.c.i
.PHONY : src/write_AB.i

# target to preprocess a source file
src/write_AB.c.i:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/write_AB.c.i
.PHONY : src/write_AB.c.i

src/write_AB.s: src/write_AB.c.s
.PHONY : src/write_AB.s

# target to generate assembly for a file
src/write_AB.c.s:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/write_AB.c.s
.PHONY : src/write_AB.c.s

src/write_boolean.o: src/write_boolean.c.o
.PHONY : src/write_boolean.o

# target to build an object file
src/write_boolean.c.o:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/write_boolean.c.o
.PHONY : src/write_boolean.c.o

src/write_boolean.i: src/write_boolean.c.i
.PHONY : src/write_boolean.i

# target to preprocess a source file
src/write_boolean.c.i:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/write_boolean.c.i
.PHONY : src/write_boolean.c.i

src/write_boolean.s: src/write_boolean.c.s
.PHONY : src/write_boolean.s

# target to generate assembly for a file
src/write_boolean.c.s:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/write_boolean.c.s
.PHONY : src/write_boolean.c.s

src/write_float.o: src/write_float.c.o
.PHONY : src/write_float.o

# target to build an object file
src/write_float.c.o:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/write_float.c.o
.PHONY : src/write_float.c.o

src/write_float.i: src/write_float.c.i
.PHONY : src/write_float.i

# target to preprocess a source file
src/write_float.c.i:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/write_float.c.i
.PHONY : src/write_float.c.i

src/write_float.s: src/write_float.c.s
.PHONY : src/write_float.s

# target to generate assembly for a file
src/write_float.c.s:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/write_float.c.s
.PHONY : src/write_float.c.s

src/write_integer.o: src/write_integer.c.o
.PHONY : src/write_integer.o

# target to build an object file
src/write_integer.c.o:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/write_integer.c.o
.PHONY : src/write_integer.c.o

src/write_integer.i: src/write_integer.c.i
.PHONY : src/write_integer.i

# target to preprocess a source file
src/write_integer.c.i:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/write_integer.c.i
.PHONY : src/write_integer.c.i

src/write_integer.s: src/write_integer.c.s
.PHONY : src/write_integer.s

# target to generate assembly for a file
src/write_integer.c.s:
	$(MAKE) -f CMakeFiles/df1.dir/build.make CMakeFiles/df1.dir/src/write_integer.c.s
.PHONY : src/write_integer.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... df1"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/calc_address.o"
	@echo "... src/calc_address.i"
	@echo "... src/calc_address.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/df1.o"
	@echo "... src/df1.i"
	@echo "... src/df1.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/read_A2.o"
	@echo "... src/read_A2.i"
	@echo "... src/read_A2.s"
	@echo "... src/read_boolean.o"
	@echo "... src/read_boolean.i"
	@echo "... src/read_boolean.s"
	@echo "... src/read_float.o"
	@echo "... src/read_float.i"
	@echo "... src/read_float.s"
	@echo "... src/read_integer.o"
	@echo "... src/read_integer.i"
	@echo "... src/read_integer.s"
	@echo "... src/read_socket.o"
	@echo "... src/read_socket.i"
	@echo "... src/read_socket.s"
	@echo "... src/select_fnct.o"
	@echo "... src/select_fnct.i"
	@echo "... src/select_fnct.s"
	@echo "... src/serial.o"
	@echo "... src/serial.i"
	@echo "... src/serial.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/write_AA.o"
	@echo "... src/write_AA.i"
	@echo "... src/write_AA.s"
	@echo "... src/write_AB.o"
	@echo "... src/write_AB.i"
	@echo "... src/write_AB.s"
	@echo "... src/write_boolean.o"
	@echo "... src/write_boolean.i"
	@echo "... src/write_boolean.s"
	@echo "... src/write_float.o"
	@echo "... src/write_float.i"
	@echo "... src/write_float.s"
	@echo "... src/write_integer.o"
	@echo "... src/write_integer.i"
	@echo "... src/write_integer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

